import { createContext, useCallback, useContext, useEffect, useRef, useState } from "react";
import type { User } from "@supabase/supabase-js";
import {
  type GameState,
  type OfflineSummary,
  type WeatherWindow,
  loadGame,
  saveGame,
  tickShop,
  tickSupplyShop,
  msUntilShopReset,
  applyOfflineTick,
  defaultState,
  buyWeatherForecastSlot,
  pruneExpiredGear,
  getExpiredGear,
} from "./gameStore";
import {
  loadCloudSave,
  saveToCloud,
  getProfile,
  type CloudProfile,
} from "./cloudSave";
import { supabase } from "../lib/supabase";
import { edgeSyncShop, edgeSyncSupplyShop } from "../lib/edgeFunctions";
import { useWeather } from "../hooks/useWeather";
import type { ForecastEntry } from "../hooks/useWeather";
import { useTimeOfDay } from "../hooks/useTimeOfDay";
import type { TimeOfDay } from "../hooks/useTimeOfDay";
import type { WeatherType } from "../data/weather";

interface GameContextValue {
  state: GameState;
  update: (newState: GameState) => void;
  /** Returns the latest state synchronously — safe to call mid-event before React re-renders. */
  getState: () => GameState;
  /** Optimistic action: applies newState immediately, calls serverFn, merges delta on success, rolls back on failure. */
  perform: <T extends Partial<GameState>>(
    optimisticState: GameState,
    serverFn: () => Promise<T>,
    onSuccess?: (result: T) => void,
    options?: {
      /** Queue the server call behind previous serialized operations — prevents concurrent DB writes overwriting each other. */
      serialize?: boolean;
      /** Surgical rollback: called with the *current* state on failure; return the corrected state.
       *  If omitted, falls back to restoring the full pre-action snapshot. */
      rollback?: (cur: GameState) => GameState;
    }
  ) => Promise<void>;
  /** Returns a promise that resolves once all currently-queued serialized harvests have completed. */
  awaitHarvests: () => Promise<unknown>;
  offlineSummary: OfflineSummary;
  clearSummary: () => void;
  shopJustRestocked: boolean;
  clearShopNotification: () => void;
  supplyJustRestocked: boolean;
  clearSupplyNotification: () => void;
  gearExpiry: { gearType: string } | null;
  clearGearExpiry: () => void;
  user: User | null;
  profile: CloudProfile | null;
  authLoading: boolean;
  signInWithGoogle: () => Promise<void>;
  signOut: () => Promise<void>;
  refreshProfile: () => Promise<void>;
  needsUsername: boolean;
  completeUsername: (username: string) => void;
  // Weather
  activeWeather: WeatherType;
  weatherMsLeft: number;
  weatherMsUntilNext: number;
  weatherIsActive: boolean;
  // Weather forecast queue (up to MAX_FORECAST_SLOTS entries pre-generated by the server)
  weatherForecast: ForecastEntry[];
  buyForecastSlot: () => void;
  // Time of day (UTC-based, for weather gating)
  timeOfDay: TimeOfDay;
}

const GameContext = createContext<GameContextValue | null>(null);

const EMPTY_SUMMARY: OfflineSummary = {
  minutesAway: 0,
  readyToHarvest: 0,
  shopRestocked: false,
  supplyRestocked: false,
};

// Reject local saves whose lastSaved is more than 30 s in the future.
// This directly closes the exploit where a user sets lastSaved = Date.now() + 60_000
// to force their manipulated localStorage to override the authoritative cloud save.
const CLOCK_SKEW_TOLERANCE_MS = 30_000;
function isTamperedTimestamp(lastSaved: number): boolean {
  return lastSaved > Date.now() + CLOCK_SKEW_TOLERANCE_MS;
}

export function GameProvider({ children }: { children: React.ReactNode }) {
  const [state, setState]                       = useState<GameState>(() => defaultState());
  const [offlineSummary, setOfflineSummary]     = useState<OfflineSummary>(EMPTY_SUMMARY);
  const [shopJustRestocked,   setShopJustRestocked]   = useState(false);
  const [supplyJustRestocked, setSupplyJustRestocked] = useState(false);
  const [gearExpiry, setGearExpiry]                   = useState<{ gearType: string } | null>(null);
  const [user, setUser]                         = useState<User | null>(null);
  const [profile, setProfile]                   = useState<CloudProfile | null>(null);
  const [authLoading, setAuthLoading]           = useState(true);
  const [needsUsername, setNeedsUsername]       = useState(false);

  const saveEnabled         = useRef(false);
  const isLoading           = useRef(false);
  const loadedFor           = useRef<string | null>(null);
  const initialSessionFired = useRef(false);
  const stateRef            = useRef(state);

  // Weather — global, shared across all players via Supabase Realtime
  const { activeType: activeWeather, isActive: weatherIsActive, msLeft: weatherMsLeft, msUntilNext: weatherMsUntilNext, forecast: weatherForecast } = useWeather();
  // Time of day — UTC-based, drives weather gating
  const timeOfDay = useTimeOfDay();

  useEffect(() => { stateRef.current = state; }, [state]);

  // ── Load session ──────────────────────────────────────────────────────────
  async function loadUserSession(u: User | null) {
    if (isLoading.current) return;
    if (u && loadedFor.current === u.id) {
      setAuthLoading(false);
      return;
    }

    isLoading.current   = true;
    saveEnabled.current = false;

    if (!u) {
      const { state: localState, summary } = loadGame();
      setState(localState);
      setOfflineSummary(summary);
      if (summary.supplyRestocked) setSupplyJustRestocked(true);
      setUser(null);
      setProfile(null);
      loadedFor.current   = null;
      saveEnabled.current = true;
      isLoading.current   = false;
      setAuthLoading(false);
      return;
    }

    loadedFor.current = u.id;
    setUser(u);

    try {
      const p = await getProfile(u.id);

      if (!p) {
        setNeedsUsername(true);
        isLoading.current = false;
        setAuthLoading(false);
        return;
      }

      setProfile(p);

      const cloudSave = await loadCloudSave(u.id);
      const localRaw  = localStorage.getItem("chrysanthemum_save");
      const localParsed = localRaw ? (JSON.parse(localRaw) as GameState & { _userId?: string }) : null;

      // Only treat local as a backup if it was written by THIS signed-in user.
      // A guest session has no _userId tag and must never override cloud progress.
      const localSave = localParsed?._userId === u.id ? localParsed : null;

      // Pick the newer save — local is kept as a rolling backup so a refresh
      // or mid-flight cloud save never loses this user's progress.
      let saveToUse: GameState;

      if (!cloudSave) {
        saveToUse = localSave ?? defaultState();
      } else if (
        localSave &&
        localSave.lastSaved > cloudSave.lastSaved &&
        !isTamperedTimestamp(localSave.lastSaved)
      ) {
        saveToUse = localSave;
      } else {
        saveToUse = cloudSave;
      }

      // Fetch current weather so offline growth can apply rain / storm bonuses.
      let offlineWeather: WeatherWindow | undefined;
      try {
        const { data: wRow } = await supabase
          .from("weather")
          .select("type,started_at,ends_at")
          .eq("id", 1)
          .single();
        if (wRow) {
          offlineWeather = {
            type:      wRow.type as import("../data/weather").WeatherType,
            startedAt: wRow.started_at as number,
            endsAt:    wRow.ends_at    as number,
          };
        }
      } catch { /* non-critical — offline tick still runs without weather bonus */ }

      const { state: ticked, summary } = applyOfflineTick(saveToUse, offlineWeather);
      setState(ticked);
      setOfflineSummary(summary);
      if (summary.shopRestocked)   setShopJustRestocked(true);
      if (summary.supplyRestocked) setSupplyJustRestocked(true);

      // Always write the offline-ticked state back to cloud. This is critical
      // when the cron job already harvested/planted while the user was offline —
      // applyOfflineTick may further modify the cloud state (or the state may
      // simply need to reflect the latest tick checkpoints). Without this write,
      // the DB can be out of sync with the client, causing plant-seed / harvest
      // edge functions to see stale occupied / empty plots.
      await saveToCloud(u.id, ticked);

      setTimeout(() => { saveEnabled.current = true; }, 1_000);

    } catch (e) {
      const { state: localState, summary } = loadGame();
      setState(localState);
      setOfflineSummary(summary);
      saveEnabled.current = true;
    }

    isLoading.current = false;
    setAuthLoading(false);
  }

  // ── Auth listener ─────────────────────────────────────────────────────────
  useEffect(() => {
    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      async (event, session) => {
        if (event === "INITIAL_SESSION") {
          initialSessionFired.current = true;
          await loadUserSession(session?.user ?? null);
          return;
        }

        if (event === "SIGNED_IN") {
          if (!initialSessionFired.current) return;
          await loadUserSession(session?.user ?? null);
          return;
        }

        if (event === "SIGNED_OUT") {
          isLoading.current            = false;
          loadedFor.current            = null;
          initialSessionFired.current  = false;
          saveEnabled.current          = false;

          Object.keys(localStorage)
            .filter((k) => k.startsWith("sb-"))
            .forEach((k) => localStorage.removeItem(k));

          setUser(null);
          setProfile(null);
          setNeedsUsername(false);
          localStorage.removeItem("chrysanthemum_save");
          setState(defaultState());
          setOfflineSummary(EMPTY_SUMMARY);
          setTimeout(() => { saveEnabled.current = true; }, 500);
          setAuthLoading(false);
          return;
        }

        if (event === "TOKEN_REFRESHED") {
          if (session?.user) setUser(session.user);
          return;
        }

        if (event === "USER_UPDATED") {
          if (session?.user) {
            setUser(session.user);
            const p = await getProfile(session.user.id);
            if (p) setProfile(p);
          }
          return;
        }
      }
    );

    return () => subscription.unsubscribe();
  }, []);

  // ── Auto-save ─────────────────────────────────────────────────────────────
  // Signed-in users: writes are now owned by Edge Functions (server-authoritative).
  // We keep a localStorage shadow only so the correct save can be recovered if a
  // cloud write was in-flight when the page was refreshed.
  // Guest users: still write to localStorage as before.
  useEffect(() => {
    if (!saveEnabled.current) return;
    if (user && !needsUsername) {
      try {
        localStorage.setItem(
          "chrysanthemum_save",
          JSON.stringify({ ...state, lastSaved: Date.now(), _userId: user.id })
        );
      } catch { /* storage full or unavailable */ }
    } else if (!user) {
      saveGame(state);
    }
  }, [state]);

  // ── Shop + supply tick ────────────────────────────────────────────────────
  useEffect(() => {
    const interval = setInterval(() => {
      if (!saveEnabled.current) return;
      setState((prev) => {
        let next = prev;

        // Seed shop restock
        const msLeft = msUntilShopReset(next);
        if (msLeft === 0) {
          const ticked = tickShop(next);
          if (ticked !== next) {
            setShopJustRestocked(true);
            harvestQueue.current = harvestQueue.current
              .then(() => edgeSyncShop(ticked.shop, ticked.lastShopReset))
              .catch(() => {});
            next = ticked;
          }
        }

        // Supply shop restock
        const supplyTicked = tickSupplyShop(next);
        if (supplyTicked !== next) {
          const shop  = supplyTicked.supplyShop;
          const reset = supplyTicked.lastSupplyReset;
          setSupplyJustRestocked(true);
          harvestQueue.current = harvestQueue.current
            .then(() => edgeSyncSupplyShop(shop, reset))
            .catch(() => {});
          next = supplyTicked;
        }

        // Prune expired gear from grid — surface the first expiry as a toast
        const tickNow = Date.now();
        const expired = getExpiredGear(next.grid, tickNow);
        const prunedGrid = pruneExpiredGear(next.grid, tickNow);
        if (prunedGrid !== next.grid) {
          if (expired.length > 0) setGearExpiry({ gearType: expired[0].gearType });
          next = { ...next, grid: prunedGrid };
        }

        return next;
      });
    }, 1_000);
    return () => clearInterval(interval);
  }, []);

  // ── Actions ───────────────────────────────────────────────────────────────
  // update() is used for authoritative full-state writes (offline tick, growth
  // effects, etc.). It keeps stateRef in sync so getState() always reflects
  // the latest value even before React re-renders.
  const update = useCallback((newState: GameState) => {
    stateRef.current = newState;
    setState(newState);
  }, []);

  const getState = useCallback(() => stateRef.current, []);

  // Global queue for harvest server calls — ensures they execute one at a time
  // so concurrent DB reads/writes don't overwrite each other's grid changes.
  const harvestQueue = useRef<Promise<unknown>>(Promise.resolve());
  const awaitHarvests = useCallback(() => harvestQueue.current, []);

  const perform = useCallback(async <T extends Partial<GameState>>(
    optimisticState: GameState,
    serverFn: () => Promise<T>,
    onSuccess?: (result: T) => void,
    options?: {
      serialize?: boolean;
      rollback?: (cur: GameState) => GameState;
    }
  ) => {
    const prev = stateRef.current;
    // Update stateRef synchronously so a second rapid perform() call sees
    // the correct "post-first-optimistic" state when it computes its own
    // optimistic delta — prevents two rapid harvests from undoing each other.
    stateRef.current = optimisticState;
    setState(optimisticState); // apply immediately to React tree

    const doServer = async () => {
      try {
        const result = await serverFn();
        // Merge server delta into whatever state is current at reconcile time
        // (avoids stomping growth ticks that fired during the network round-trip)
        setState((cur) => ({ ...cur, ...result, ok: undefined }));
        onSuccess?.(result);
      } catch (err) {
        console.error("Action failed, rolling back:", err);
        if (options?.rollback) {
          // Surgical rollback: only undo this specific action's change in the
          // *current* state — avoids clobbering other concurrent actions that
          // may have already succeeded.
          const rolled = options.rollback(stateRef.current);
          stateRef.current = rolled;
          setState(rolled);
        } else {
          stateRef.current = prev;
          setState(prev);
        }
      }
    };

    if (options?.serialize) {
      // Queue the server call — doServer resolves even on error (handled internally)
      harvestQueue.current = harvestQueue.current.then(doServer).catch(() => {});
    } else {
      await doServer();
    }
  }, []);

  function buyForecastSlot() {
    setState((prev) => {
      const next = buyWeatherForecastSlot(prev);
      return next ?? prev;
    });
  }

  async function refreshProfile() {
    if (!user) return;
    const p = await getProfile(user.id);
    if (p) setProfile(p);
  }

  function completeUsername(_username: string) {
    setNeedsUsername(false);
    if (user) {
      getProfile(user.id).then(async (p) => {
        setProfile(p);
        const fresh = defaultState();
        setState(fresh);
        await saveToCloud(user.id, fresh);
        localStorage.removeItem("chrysanthemum_save");
        setTimeout(() => { saveEnabled.current = true; }, 500);
        setAuthLoading(false);
      });
    }
  }

  async function signInWithGoogle() {
    await supabase.auth.signInWithOAuth({
      provider: "google",
      options: { redirectTo: window.location.origin },
    });
  }

  async function signOut() {
    saveEnabled.current = false;
    await supabase.auth.signOut();
  }

  return (
    <GameContext.Provider value={{
      state, update, getState, perform, awaitHarvests,
      offlineSummary, clearSummary: () => setOfflineSummary(EMPTY_SUMMARY),
      shopJustRestocked,   clearShopNotification:   () => setShopJustRestocked(false),
      supplyJustRestocked, clearSupplyNotification: () => setSupplyJustRestocked(false),
      gearExpiry, clearGearExpiry: () => setGearExpiry(null),
      user, profile, authLoading,
      signInWithGoogle, signOut,
      refreshProfile,
      needsUsername, completeUsername,
      activeWeather,
      weatherMsLeft,
      weatherMsUntilNext,
      weatherIsActive,
      weatherForecast,
      buyForecastSlot,
      timeOfDay,
    }}>
      {children}
    </GameContext.Provider>
  );
}

export function useGame() {
  const ctx = useContext(GameContext);
  if (!ctx) throw new Error("useGame must be used inside GameProvider");
  return ctx;
}
