import { createContext, useCallback, useContext, useEffect, useRef, useState } from "react";
import type { User } from "@supabase/supabase-js";
import {
  type GameState,
  type OfflineSummary,
  type WeatherWindow,
  loadGame,
  saveGame,
  tickShop,
  tickSupplyShop,
  msUntilShopReset,
  applyOfflineTick,
  defaultState,
  buyWeatherForecastSlot,
  pruneExpiredGear,
  getExpiredGear,
  mergeServerResult,
} from "./gameStore";
import {
  loadCloudSave,
  saveToCloud,
  getProfile,
  type CloudProfile,
} from "./cloudSave";
import { supabase } from "../lib/supabase";
import { edgeSyncShop, edgeSyncSupplyShop } from "../lib/edgeFunctions";
import { useWeather } from "../hooks/useWeather";
import type { ForecastEntry } from "../hooks/useWeather";
import { useTimeOfDay } from "../hooks/useTimeOfDay";
import type { TimeOfDay } from "../hooks/useTimeOfDay";
import type { WeatherType } from "../data/weather";
import { queueEntryDisplay } from "../lib/craftDisplay";
import { getFlower, type MutationType } from "../data/flowers";

interface GameContextValue {
  state: GameState;
  update: (newState: GameState) => void;
  /** Returns the latest state synchronously — safe to call mid-event before React re-renders. */
  getState: () => GameState;
  /** Re-reads the authoritative save from DB and replaces local state. Use when the client
   *  detects it's out of sync with the server (e.g. cron planted seeds the client doesn't know about). */
  reloadFromCloud: () => Promise<void>;
  /** Flush the current grid to the cloud immediately. Used after client-side
   *  mutation ticks (e.g. sprinkler mutations) so the mutation is in the DB
   *  before the server's harvest function reads it. No-ops when not logged in
   *  or saves are temporarily disabled. */
  saveGridNow: () => Promise<void>;
  /** Optimistic action: applies newState immediately, calls serverFn, merges delta on success, rolls back on failure. */
  perform: <T extends Partial<GameState>>(
    optimisticState: GameState,
    serverFn: () => Promise<T>,
    onSuccess?: (result: T) => void,
    options?: {
      /** Queue the server call behind previous serialized operations — prevents concurrent DB writes overwriting each other. */
      serialize?: boolean;
      /** Surgical rollback: called with the *current* state on failure; return the corrected state.
       *  If omitted, falls back to restoring the full pre-action snapshot. */
      rollback?: (cur: GameState) => GameState;
    }
  ) => Promise<void>;
  /** Returns a promise that resolves once all currently-queued serialized harvests have completed. */
  awaitHarvests: () => Promise<unknown>;
  /** Attach an async operation to the serialized harvest queue so signOut() waits for it. */
  queueWork: (fn: () => Promise<void>) => void;
  offlineSummary: OfflineSummary;
  clearSummary: () => void;
  shopJustRestocked: boolean;
  clearShopNotification: () => void;
  supplyJustRestocked: boolean;
  clearSupplyNotification: () => void;
  gearExpiry: { gearType: string } | null;
  clearGearExpiry: () => void;
  /** Stack of craft entries that just transitioned from in-progress → ready
   *  during this session. App renders one CraftCompletionBanner per entry. */
  craftCompletions: { id: string; emoji: string; name: string }[];
  dismissCraftCompletion: (id: string) => void;
  /** Same shape as craftCompletions but for the alchemy attunement queue. */
  attunementCompletions: { id: string; emoji: string; name: string }[];
  dismissAttunementCompletion: (id: string) => void;
  user: User | null;
  profile: CloudProfile | null;
  authLoading: boolean;
  signInWithGoogle: () => Promise<void>;
  signOut: () => Promise<void>;
  refreshProfile: () => Promise<void>;
  needsUsername: boolean;
  completeUsername: (username: string) => void;
  isStaleTab: boolean;
  /** When non-null, App renders the SignInPromptModal. Components call
   *  `requestSignIn()` instead of `signInWithGoogle()` directly so guests
   *  see a friendly prompt before being kicked to the OAuth flow. */
  signInPromptReason: string | null;
  /** Open the sign-in prompt. Optional `reason` is shown as a contextual
   *  second line on the modal (e.g. "to buy seeds", "to upgrade your farm"). */
  requestSignIn: (reason?: string) => void;
  dismissSignInPrompt: () => void;
  // Weather
  activeWeather: WeatherType;
  weatherMsLeft: number;
  weatherMsUntilNext: number;
  weatherIsActive: boolean;
  // Weather forecast queue (up to MAX_FORECAST_SLOTS entries pre-generated by the server)
  weatherForecast: ForecastEntry[];
  buyForecastSlot: () => void;
  // Time of day (UTC-based, for weather gating)
  timeOfDay: TimeOfDay;
  // Harvest / pickup popup pills shown over the UI
  harvestPopups: Map<string, { speciesId: string; mutation?: MutationType; count: number; isSeed?: boolean }>;
  pushHarvestPopup: (speciesId: string, mutation?: MutationType, isSeed?: boolean, qty?: number) => void;
  dismissHarvestPopup: (key: string) => void;
  genericToasts: Map<string, { emoji: string; label: string; count: number; color?: string; variant?: "gain" | "loss" }>;
  pushGenericToast: (key: string, emoji: string, label: string, color?: string, variant?: "gain" | "loss", qty?: number) => void;
  dismissGenericToast: (key: string) => void;
}

const GameContext = createContext<GameContextValue | null>(null);

const EMPTY_SUMMARY: OfflineSummary = {
  minutesAway: 0,
  readyToHarvest: 0,
  shopRestocked: false,
  supplyRestocked: false,
  craftsReady: 0,
  attunementsReady: 0,
};

// Reject local saves whose lastSaved is more than 1 s in the future.
// This directly closes the exploit where a user sets lastSaved = Date.now() + 60_000
// to force their manipulated localStorage to override the authoritative cloud save.
const CLOCK_SKEW_TOLERANCE_MS = 1_000;
function isTamperedTimestamp(lastSaved: number): boolean {
  return lastSaved > Date.now() + CLOCK_SKEW_TOLERANCE_MS;
}

export function GameProvider({ children }: { children: React.ReactNode }) {
  const [state, setState]                       = useState<GameState>(() => defaultState());
  const [offlineSummary, setOfflineSummary]     = useState<OfflineSummary>(EMPTY_SUMMARY);
  const [shopJustRestocked,   setShopJustRestocked]   = useState(false);
  const [supplyJustRestocked, setSupplyJustRestocked] = useState(false);
  const [gearExpiry, setGearExpiry]                   = useState<{ gearType: string } | null>(null);
  type HarvestEntry = { speciesId: string; mutation?: MutationType; count: number; isSeed?: boolean };
  const [harvestPopups, setHarvestPopups] = useState<Map<string, HarvestEntry>>(new Map());
  function pushHarvestPopup(speciesId: string, mutation?: MutationType, isSeed?: boolean, qty = 1) {
    const key = isSeed ? `${speciesId}:seed` : `${speciesId}:${mutation ?? ""}`;
    setHarvestPopups((prev) => {
      const next = new Map(prev);
      const existing = next.get(key);
      next.set(key, existing ? { ...existing, count: existing.count + qty } : { speciesId, mutation, count: qty, isSeed });
      return next;
    });
  }
  type GenericToastEntry = { emoji: string; label: string; count: number; color?: string; variant?: "gain" | "loss" };
  const [genericToasts, setGenericToasts] = useState<Map<string, GenericToastEntry>>(new Map());
  function pushGenericToast(key: string, emoji: string, label: string, color?: string, variant?: "gain" | "loss", qty = 1) {
    setGenericToasts((prev) => {
      const next = new Map(prev);
      const existing = next.get(key);
      next.set(key, existing ? { ...existing, count: existing.count + qty } : { emoji, label, count: qty, color, variant });
      return next;
    });
  }
  const [craftCompletions, setCraftCompletions]       = useState<{ id: string; emoji: string; name: string }[]>([]);
  const [attunementCompletions, setAttunementCompletions] = useState<{ id: string; emoji: string; name: string }[]>([]);
  const [user, setUser]                         = useState<User | null>(null);
  const [profile, setProfile]                   = useState<CloudProfile | null>(null);
  const [authLoading, setAuthLoading]           = useState(true);
  const [needsUsername, setNeedsUsername]       = useState(false);
  const [signInPromptReason, setSignInPromptReason] = useState<string | null>(null);

  const saveEnabled         = useRef(false);
  const isLoading           = useRef(false);
  const loadedFor           = useRef<string | null>(null);
  const initialSessionFired = useRef(false);
  const stateRef            = useRef(state);
  const tabId               = useRef(crypto.randomUUID());
  // Craft completion banners — track which queue ids we've observed in-progress
  // (so already-done entries on initial load don't fire a banner) and which
  // we've already fired a banner for (so each transition fires exactly once).
  const craftSeenInProgress = useRef<Set<string>>(new Set());
  const craftFiredCompleted = useRef<Set<string>>(new Set());
  // Same machinery for the alchemy attunement queue.
  const attuneSeenInProgress = useRef<Set<string>>(new Set());
  const attuneFiredCompleted = useRef<Set<string>>(new Set());
  // Incremented on every sign-out so in-flight loadUserSession calls know to discard their results.
  const loadGen             = useRef(0);
  const [isStaleTab, setIsStaleTab] = useState(false);

  // Weather — global, shared across all players via Supabase Realtime
  const { activeType: activeWeather, isActive: weatherIsActive, msLeft: weatherMsLeft, msUntilNext: weatherMsUntilNext, forecast: weatherForecast } = useWeather();
  // Time of day — UTC-based, drives weather gating
  const timeOfDay = useTimeOfDay();

  useEffect(() => { stateRef.current = state; }, [state]);

  // ── Load session ──────────────────────────────────────────────────────────
  async function loadUserSession(u: User | null) {
    if (isLoading.current) return;
    if (u && loadedFor.current === u.id) {
      setAuthLoading(false);
      return;
    }

    // Stamp this load with the current generation. Any sign-out that fires
    // while we're awaiting will increment loadGen, letting us discard stale results
    // and prevent a finished loadUserSession from overwriting the cleared state.
    const gen = loadGen.current;

    isLoading.current   = true;
    saveEnabled.current = false;

    if (!u) {
      const { state: localState, summary } = loadGame();
      setState(localState);
      setOfflineSummary(summary);
      if (summary.supplyRestocked) setSupplyJustRestocked(true);
      setUser(null);
      setProfile(null);
      loadedFor.current   = null;
      saveEnabled.current = true;
      isLoading.current   = false;
      setAuthLoading(false);
      return;
    }

    loadedFor.current = u.id;
    setUser(u);
    // Claim this tab as the active session — other open tabs will detect this
    // via the storage event and disable their saves to prevent data races.
    localStorage.setItem(`chrysanthemum_active_tab_${u.id}`, tabId.current);

    try {
      const p = await getProfile(u.id);
      if (loadGen.current !== gen) return; // sign-out fired while we were loading — discard

      if (!p) {
        setNeedsUsername(true);
        isLoading.current = false;
        setAuthLoading(false);
        return;
      }

      setProfile(p);

      const cloudSave = await loadCloudSave(u.id);
      if (loadGen.current !== gen) return; // sign-out fired — discard

      const localRaw  = localStorage.getItem("chrysanthemum_save");
      const localParsed = localRaw ? (JSON.parse(localRaw) as GameState & { _userId?: string }) : null;

      // Only treat local as a backup if it was written by THIS signed-in user.
      // A guest session has no _userId tag and must never override cloud progress.
      const localSave = localParsed?._userId === u.id ? localParsed : null;

      // Pick the newer save — local is kept as a rolling backup so a refresh
      // or mid-flight cloud save never loses this user's progress.
      let saveToUse: GameState;

      if (!cloudSave) {
        saveToUse = localSave ?? defaultState();
      } else if (
        localSave &&
        localSave.lastSaved > cloudSave.lastSaved &&
        !isTamperedTimestamp(localSave.lastSaved)
      ) {
        saveToUse = localSave;
      } else {
        saveToUse = cloudSave;
      }

      // Fetch current weather so offline growth can apply rain / storm bonuses.
      let offlineWeather: WeatherWindow | undefined;
      try {
        const { data: wRow } = await supabase
          .from("weather")
          .select("type,started_at,ends_at")
          .eq("id", 1)
          .single();
        if (wRow) {
          offlineWeather = {
            type:      wRow.type as import("../data/weather").WeatherType,
            startedAt: wRow.started_at as number,
            endsAt:    wRow.ends_at    as number,
          };
        }
      } catch { /* non-critical — offline tick still runs without weather bonus */ }

      if (loadGen.current !== gen) return; // sign-out fired — discard

      const { state: ticked, summary } = applyOfflineTick(saveToUse, offlineWeather);
      setState(ticked);
      setOfflineSummary(summary);
      if (summary.shopRestocked)   setShopJustRestocked(true);
      if (summary.supplyRestocked) setSupplyJustRestocked(true);

      // Always write the offline-ticked state back to cloud. This is critical
      // when the cron job already harvested/planted while the user was offline —
      // applyOfflineTick may further modify the cloud state (or the state may
      // simply need to reflect the latest tick checkpoints). Without this write,
      // the DB can be out of sync with the client, causing plant-seed / harvest
      // edge functions to see stale occupied / empty plots.
      let savedUpdatedAt = await saveToCloud(u.id, ticked);
      if (loadGen.current !== gen) return; // sign-out fired after cloud write — don't re-enable saves

      if (savedUpdatedAt) {
        // Keep serverUpdatedAt in sync so subsequent CAS writes use the correct stamp.
        stateRef.current = { ...ticked, serverUpdatedAt: savedUpdatedAt };
        setState(stateRef.current);
      } else {
        // CAS failed — the offline cron or another process wrote to DB between our
        // loadCloudSave and this write-back (e.g. auto-planter planted cells while
        // we were offline). Re-read the authoritative state so the client has the
        // correct grid and a fresh serverUpdatedAt, then retry once.
        const freshCloud = await loadCloudSave(u.id);
        if (loadGen.current !== gen) return;
        if (freshCloud) {
          const { state: reticked } = applyOfflineTick(freshCloud, offlineWeather);
          stateRef.current = reticked;
          setState(reticked);
          savedUpdatedAt = await saveToCloud(u.id, reticked);
          if (loadGen.current !== gen) return;
          if (savedUpdatedAt) {
            stateRef.current = { ...reticked, serverUpdatedAt: savedUpdatedAt };
            setState(stateRef.current);
          }
        }
      }

      setTimeout(() => { saveEnabled.current = true; }, 1_000);

    } catch (e) {
      if (loadGen.current !== gen) return; // sign-out fired — discard
      const { state: localState, summary } = loadGame();
      setState(localState);
      setOfflineSummary(summary);
      saveEnabled.current = true;
    }

    isLoading.current = false;
    setAuthLoading(false);
  }

  // ── Auth listener ─────────────────────────────────────────────────────────
  useEffect(() => {
    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      async (event, session) => {
        if (event === "INITIAL_SESSION") {
          initialSessionFired.current = true;
          await loadUserSession(session?.user ?? null);
          return;
        }

        if (event === "SIGNED_IN") {
          if (!initialSessionFired.current) return;
          await loadUserSession(session?.user ?? null);
          return;
        }

        if (event === "SIGNED_OUT") {
          loadGen.current++;           // invalidate any in-flight loadUserSession
          isLoading.current            = false;
          loadedFor.current            = null;
          initialSessionFired.current  = false;
          saveEnabled.current          = false;

          Object.keys(localStorage)
            .filter((k) => k.startsWith("sb-"))
            .forEach((k) => localStorage.removeItem(k));

          setUser(null);
          setProfile(null);
          setNeedsUsername(false);
          localStorage.removeItem("chrysanthemum_save");
          setState(defaultState());
          setOfflineSummary(EMPTY_SUMMARY);
          // Reset craft completion tracking so stale ids from the prior session
          // don't suppress banners after sign-in.
          craftSeenInProgress.current.clear();
          craftFiredCompleted.current.clear();
          attuneSeenInProgress.current.clear();
          attuneFiredCompleted.current.clear();
          setCraftCompletions([]);
          setTimeout(() => { saveEnabled.current = true; }, 500);
          setAuthLoading(false);
          return;
        }

        if (event === "TOKEN_REFRESHED") {
          if (session?.user) setUser(session.user);
          return;
        }

        if (event === "USER_UPDATED") {
          if (session?.user) {
            setUser(session.user);
            const p = await getProfile(session.user.id);
            if (p) setProfile(p);
          }
          return;
        }
      }
    );

    return () => subscription.unsubscribe();
  }, []);

  // ── Single-session enforcement ────────────────────────────────────────────
  // When a second tab logs in as the same user it writes a new tabId to
  // localStorage. The storage event fires in every OTHER tab, allowing this
  // tab to detect it's been superseded and disable its saves.
  useEffect(() => {
    if (!user) return;
    function handleStorage(e: StorageEvent) {
      if (e.key === `chrysanthemum_active_tab_${user!.id}` && e.newValue !== tabId.current) {
        saveEnabled.current = false;
        setIsStaleTab(true);
      }
    }
    window.addEventListener("storage", handleStorage);
    return () => window.removeEventListener("storage", handleStorage);
  }, [user]);

  // ── Auto-save ─────────────────────────────────────────────────────────────
  // Signed-in users: writes are now owned by Edge Functions (server-authoritative).
  // We keep a localStorage shadow only so the correct save can be recovered if a
  // cloud write was in-flight when the page was refreshed.
  // Guest users: still write to localStorage as before.
  useEffect(() => {
    if (!saveEnabled.current) return;
    if (isStaleTab) return;
    if (user && !needsUsername) {
      try {
        localStorage.setItem(
          "chrysanthemum_save",
          JSON.stringify({ ...state, lastSaved: Date.now(), _userId: user.id })
        );
      } catch { /* storage full or unavailable */ }
    } else if (!user) {
      saveGame(state);
    }
  }, [state]);

  // ── Shop + supply tick ────────────────────────────────────────────────────
  useEffect(() => {
    const interval = setInterval(() => {
      if (!saveEnabled.current) return;
      setState((prev) => {
        let next = prev;

        // Seed shop restock
        const msLeft = msUntilShopReset(next);
        if (msLeft === 0) {
          const ticked = tickShop(next);
          if (ticked !== next) {
            setShopJustRestocked(true);
            harvestQueue.current = harvestQueue.current
              .then(() => edgeSyncShop(ticked.shop, ticked.lastShopReset))
              .catch(() => {});
            next = ticked;
          }
        }

        // Supply shop restock
        const supplyTicked = tickSupplyShop(next);
        if (supplyTicked !== next) {
          const shop  = supplyTicked.supplyShop;
          const reset = supplyTicked.lastSupplyReset;
          setSupplyJustRestocked(true);
          harvestQueue.current = harvestQueue.current
            .then(() => edgeSyncSupplyShop(shop, reset))
            .catch(() => {});
          next = supplyTicked;
        }

        // Prune expired gear from grid — surface the first expiry as a toast
        const tickNow = Date.now();
        const expired = getExpiredGear(next.grid, tickNow);
        const prunedGrid = pruneExpiredGear(next.grid, tickNow);
        if (prunedGrid !== next.grid) {
          if (expired.length > 0) setGearExpiry({ gearType: expired[0].gearType });
          next = { ...next, grid: prunedGrid };
        }

        // ── Craft completion detection ─────────────────────────────────────
        // Fire a banner once per entry that transitions in-progress → done
        // during this session. Already-completed entries observed on first
        // load go straight into "fired" so they don't pop banners on refresh —
        // the navbar badge (B6) is the right surface for that.
        const newCompletions: { id: string; emoji: string; name: string }[] = [];
        for (const entry of next.craftingQueue ?? []) {
          if (craftFiredCompleted.current.has(entry.id)) continue;
          const doneAt = new Date(entry.startedAt).getTime() + entry.durationMs;
          const isDone = tickNow >= doneAt;
          if (isDone) {
            if (craftSeenInProgress.current.has(entry.id)) {
              // Genuine transition — fire banner.
              const { emoji, name } = queueEntryDisplay(entry);
              newCompletions.push({ id: entry.id, emoji, name });
            }
            // Either way, never fire again for this id.
            craftFiredCompleted.current.add(entry.id);
          } else {
            craftSeenInProgress.current.add(entry.id);
          }
        }
        if (newCompletions.length > 0) {
          setCraftCompletions((prev) => [...prev, ...newCompletions]);
        }

        // ── Attunement completion detection (mirrors craft logic) ─────────
        const newAttuneCompletions: { id: string; emoji: string; name: string }[] = [];
        for (const entry of next.attunementQueue ?? []) {
          if (attuneFiredCompleted.current.has(entry.id)) continue;
          const doneAt = new Date(entry.startedAt).getTime() + entry.durationMs;
          const isDone = tickNow >= doneAt;
          if (isDone) {
            if (attuneSeenInProgress.current.has(entry.id)) {
              // Look up the species emoji + name. We don't reveal the rolled
              // mutation here (server only rolls on collect) — banner just
              // says "Attunement ready: <flower>".
              const flower = getFlower(entry.speciesId);
              newAttuneCompletions.push({
                id:    entry.id,
                emoji: flower?.emoji.bloom ?? "🌸",
                name:  flower?.name ?? entry.speciesId,
              });
            }
            attuneFiredCompleted.current.add(entry.id);
          } else {
            attuneSeenInProgress.current.add(entry.id);
          }
        }
        if (newAttuneCompletions.length > 0) {
          setAttunementCompletions((prev) => [...prev, ...newAttuneCompletions]);
        }

        return next;
      });
    }, 1_000);
    return () => clearInterval(interval);
  }, []);

  // ── Actions ───────────────────────────────────────────────────────────────
  // update() is used for authoritative full-state writes (offline tick, growth
  // effects, etc.). It keeps stateRef in sync so getState() always reflects
  // the latest value even before React re-renders.
  const update = useCallback((newState: GameState) => {
    stateRef.current = newState;
    setState(newState);
  }, []);

  const getState = useCallback(() => stateRef.current, []);

  /** Re-reads the authoritative save from DB and replaces local state.
   *  Called when the client detects the server has changed state it doesn't know about
   *  (e.g. the offline cron planted seeds while the user was watching). */
  const reloadFromCloud = useCallback(async () => {
    if (!user || !saveEnabled.current) return;
    const fresh = await loadCloudSave(user.id);
    if (!fresh) return;
    // Route through mergeServerResult so shop/supply reset timestamps can never
    // roll backwards — edgeSyncShop may not have committed to DB yet when a
    // cropstick poll or error-recovery reload fires, so a raw setState(fresh)
    // would briefly stamp the old shop over the client's already-ticked new shop.
    setState((cur) => {
      const next = mergeServerResult(cur, fresh);
      stateRef.current = next;
      return next;
    });
  }, [user]);

  /** Persist the current grid to the DB immediately. Called by Garden after a
   *  sprinkler mutation tick so that server-side harvest can read the mutation.
   *  Skipped when not logged in or saves are disabled (loading / sign-out). */
  const saveGridNow = useCallback(async () => {
    if (!user || !saveEnabled.current) return;
    const saved = await saveToCloud(user.id, stateRef.current);
    if (saved) {
      stateRef.current = { ...stateRef.current, serverUpdatedAt: saved };
      setState((prev) => ({ ...prev, serverUpdatedAt: saved }));
    }
  }, [user]);

  // Global queue for harvest server calls — ensures they execute one at a time
  // so concurrent DB reads/writes don't overwrite each other's grid changes.
  const harvestQueue = useRef<Promise<unknown>>(Promise.resolve());
  const awaitHarvests = useCallback(() => harvestQueue.current, []);
  const queueWork = useCallback((fn: () => Promise<void>) => {
    harvestQueue.current = harvestQueue.current.then(fn).catch(() => {});
  }, []);

  const perform = useCallback(async <T extends Partial<GameState>>(
    optimisticState: GameState,
    serverFn: () => Promise<T>,
    onSuccess?: (result: T) => void,
    options?: {
      serialize?: boolean;
      rollback?: (cur: GameState) => GameState;
    }
  ) => {
    const prev = stateRef.current;
    // Update stateRef synchronously so a second rapid perform() call sees
    // the correct "post-first-optimistic" state when it computes its own
    // optimistic delta — prevents two rapid harvests from undoing each other.
    stateRef.current = optimisticState;
    setState(optimisticState); // apply immediately to React tree

    const doServer = async () => {
      try {
        const result = await serverFn();
        setState((cur) => mergeServerResult(cur, result));
        onSuccess?.(result);
      } catch (err) {
        console.error("Action failed, rolling back:", err);
        if (options?.rollback) {
          // Surgical rollback: only undo this specific action's change in the
          // *current* state — avoids clobbering other concurrent actions that
          // may have already succeeded.
          const rolled = options.rollback(stateRef.current);
          stateRef.current = rolled;
          setState(rolled);
        } else {
          stateRef.current = prev;
          setState(prev);
        }
      }
    };

    if (options?.serialize) {
      // Queue the server call — doServer resolves even on error (handled internally)
      harvestQueue.current = harvestQueue.current.then(doServer).catch(() => {});
    } else {
      await doServer();
    }
  }, []);

  function buyForecastSlot() {
    setState((prev) => {
      const next = buyWeatherForecastSlot(prev);
      return next ?? prev;
    });
  }

  async function refreshProfile() {
    if (!user) return;
    const p = await getProfile(user.id);
    if (p) setProfile(p);
  }

  function completeUsername(_username: string) {
    setNeedsUsername(false);
    if (user) {
      getProfile(user.id).then(async (p) => {
        setProfile(p);
        const fresh = defaultState();
        setState(fresh);
        const freshSavedAt = await saveToCloud(user.id, fresh);
        if (freshSavedAt) setState((prev) => ({ ...prev, serverUpdatedAt: freshSavedAt }));
        localStorage.removeItem("chrysanthemum_save");
        setTimeout(() => { saveEnabled.current = true; }, 500);
        setAuthLoading(false);
      });
    }
  }

  async function signInWithGoogle() {
    await supabase.auth.signInWithOAuth({
      provider: "google",
      options: { redirectTo: window.location.origin },
    });
  }

  async function signOut() {
    saveEnabled.current = false;
    // Flush any pending serialized operations (plant-seed, harvest, etc.) before
    // invalidating the session — otherwise in-flight edge function calls fail mid-queue,
    // their DB writes are lost, and the cloud save ends up behind the local state.
    await harvestQueue.current;
    await supabase.auth.signOut();
  }

  return (
    <GameContext.Provider value={{
      state, update, getState, perform, awaitHarvests, queueWork, reloadFromCloud, saveGridNow,
      offlineSummary, clearSummary: () => setOfflineSummary(EMPTY_SUMMARY),
      shopJustRestocked,   clearShopNotification:   () => setShopJustRestocked(false),
      supplyJustRestocked, clearSupplyNotification: () => setSupplyJustRestocked(false),
      gearExpiry, clearGearExpiry: () => setGearExpiry(null),
      craftCompletions,
      dismissCraftCompletion: (id: string) =>
        setCraftCompletions((prev) => prev.filter((c) => c.id !== id)),
      attunementCompletions,
      dismissAttunementCompletion: (id: string) =>
        setAttunementCompletions((prev) => prev.filter((c) => c.id !== id)),
      user, profile, authLoading,
      signInWithGoogle, signOut,
      refreshProfile,
      needsUsername, completeUsername,
      isStaleTab,
      signInPromptReason,
      requestSignIn:       (reason?: string) => setSignInPromptReason(reason ?? ""),
      dismissSignInPrompt: () => setSignInPromptReason(null),
      activeWeather,
      weatherMsLeft,
      weatherMsUntilNext,
      weatherIsActive,
      weatherForecast,
      buyForecastSlot,
      timeOfDay,
      harvestPopups,
      pushHarvestPopup,
      dismissHarvestPopup: (key: string) =>
        setHarvestPopups((prev) => { const next = new Map(prev); next.delete(key); return next; }),
      genericToasts,
      pushGenericToast,
      dismissGenericToast: (key: string) =>
        setGenericToasts((prev) => { const next = new Map(prev); next.delete(key); return next; }),
    }}>
      {children}
    </GameContext.Provider>
  );
}

export function useGame() {
  const ctx = useContext(GameContext);
  if (!ctx) throw new Error("useGame must be used inside GameProvider");
  return ctx;
}
